In [1]:
import numpy as np
from  joblib import dump, load

In [2]:
model = load('price_prediction.joblib')

In [10]:
# here I am substituting feature's values to get predicted price

In [3]:
features= np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])

In [4]:
model.predict(features)

array([22.468])

In [6]:
features= np.array([[-1.43942006,  3.12628155, -4.12165014, -0.27288841, -1.42262747,
       -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -4.86091034]])

In [7]:
model.predict(features)

array([25.852])

In [8]:
features= np.array([[-1.43942006,  3.12628155, -4.12165014, -1.27288841, -1.42262747,
       -0.041, -9.31238772,  2.61111401, -1.0016859 , -5.0 ,
       -0.5,  6.41164221, -4.86091034]])

In [9]:
model.predict(features)

array([27.166])